language: python
python:
  - "2.7"
  - "3.4"

# Setup anaconda just to get fast binary installation of common pacakges
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm

# Install packages
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy matplotlib
  - pip install neo
  - pip install git+https://github.com/neuralensemble/libNeuroML@development
  - pip install git+https://github.com/purcell/airspeed.git
  - pip install --allow-all-external git+https://github.com/rgerkin/pyNeuroML.git
  - pip install --allow-all-external git+https://github.com/neuralensemble/python-neo.git
  - pip install --allow-all-external git+https://github.com/neuralensemble/elephant.git
  - pip install git+https://github.com/rgerkin/sciunit.git
  - python setup.py install

# Setting up pre-requirements
before_script:
  - echo $PYTHONPATH
  - ls

# command to run tests, e.g. python setup.py test
script: python example.py
