name: neuronunit_docs
dependencies:
- python==3.5
- matplotlib>=1.5
- sphinx>=1.5
- pip:
  - neo==0.4
  - elephant
  - dask
  - numba
  - streamlit
  - sklearn
  - seaborn
  - frozendict
  - plotly
  - asciiplotlib
  - ipfx
  - git+https://github.com/russelljjarvis/jit_jub@neuronunit
  - git+https://github.com/russelljjarvis/BluePyOpt
  - git+https://github.com/russelljjarvis/sciunit@dev
