defaults: &defaults
  working_directory: ~/markovmodel/PyEMMA
  docker:
    - image: continuumio/miniconda3

inst_conda_bld: &inst_conda_bld
  - run: conda config --add channels conda-forge
  - run: conda config --set always_yes true
  - run: conda config --set quiet true
  - run: conda install conda-build

version: 2

jobs:
  build:
    <<: *defaults
    parallelism: 1
    steps:
      - checkout
      - run: git fetch --unshallow || true
      - run: apt-get install -y cpp gcc
      - run: apt-get install -y libx11-6 python-dev git build-essential
      - run: apt-get install -y autoconf automake gcc g++ make gfortran
      - run: apt-get install -y python-tables
      - run: apt-get install -y libhdf5-serial-dev

      - run: conda config --add channels conda-forge
      - run: conda config --set always_yes true
      - run: conda config --set quiet true
      - run: conda install conda-build
      - run: pip install pip --upgrade;
      - run: conda install numpy;
      - run: conda install numba;
      - run: conda install dask;
      - run: pip install tables
      - run: pip install scipy==1.5.4
      - run: pip install coverage
      - run: pip install cython
      - run: pip install asciiplotlib;
      - run: pip install ipfx
      - run: pip install streamlit
      - run: pip install sklearn
      - run: pip install seaborn
      - run: pip install frozendict
      - run: pip install plotly
      - run: pip install allensdk==0.16.3
      - run: pip install --upgrade colorama
      - run: pip install -e .
      - run: rm -rf /opt/conda/lib/python3.8/site-packages/sciunit
      - run: git clone -b neuronunit https://github.com/russelljjarvis/jit_hub.git
      - run: cd jit_hub; pip install -e .; cd ..;
      - run: git clone -b neuronunit_reduced_cells https://github.com/russelljjarvis/BluePyOpt.git
      - run: cd BluePyOpt; pip install -e .
      - run: git clone -b dev https://github.com/russelljjarvis/sciunit.git

      - run: cd sciunit; pip install -e .; cd ..;
      - run: pip install git+https://github.com/russelljjarvis/eFEL
      - run: cd neuronunit/unit_test; python rheobase_dtc_test.py
      - run: cd neuronunit/unit_test; python adexp_opt.py
      - run: cd neuronunit/unit_test; python import_test.py
      - run: cd neuronunit/unit_test; python -m unittest scores_unit_test.py
