defaults: &defaults
  working_directory: ~/markovmodel/PyEMMA
  docker:
    - image: continuumio/miniconda3

version: 2
jobs:
  build:
    <<: *defaults
    parallelism: 1
    steps:
      - checkout
      - run: git fetch --unshallow || true
      - run: apt-get install -y cpp gcc
      - run: apt-get install -y libx11-6 python-dev git build-essential
      - run: apt-get install -y autoconf automake gcc g++ make gfortran
      - run: apt-get install -y python-tables
      - run: conda config --add channels conda-forge
      - run: conda config --set always_yes true
      - run: conda config --set quiet true
      - run: conda install conda-build
      - run: which pip
      - run: conda install scipy;
      - run: conda install numpy;
      - run: conda install numba;
      - run: conda install dask;
      - run: pip install tables
      - run: pip install cython
      - run: pip install asciiplotlib
     - run: pip install pip --upgrade; pip install -r requirements.txt;
     - run: pip install -e .
